### ISSUE TITLE
Segfault on comparison of SymEngine objects with incompatible values

### ISSUE THREAD

**Issue by zverok** [symengine/symengine.rb#43] opened 2016-05-25 13:38 UTC
```ruby
i = SymEngine::Integer.new(5)
# => #<SymEngine::Integer:0x8705938> 
i == 5
# => true 
i == SymEngine::Integer.new(5)
# => true 
i == 'foo'
# [BUG] Segmentation fault at 0x000000
```

**Comment by isuruf** [comment] 2016-05-25 13:39
Duplicate of #22

**Comment by isuruf** [comment] 2016-06-15 04:40
Fixed via #53

**Closed by isuruf** 2016-06-15 04:40 UTC
